algorithm_description: Searches the MAAP STAC catalog for a granule, downloads a raster asset, clips it to a bounding box, and emits a new STAC Item describing the clipped output.
algorithm_name: stac-clip
algorithm_version: main
keywords: ogc, stac, raster
code_repository: https://github.com/marjo-luc/ogc-app-pack-examples.git
citation: https://github.com/marjo-luc/ogc-app-pack-examples.git
author: mlucas
contributor: mlucas
license: https://raw.githubusercontent.com/marjo-luc/ogc-app-pack-examples/refs/heads/main/LICENSE
release_notes: None
run_command: run.py
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 10 # mebibytes

inputs:
  - name: collection_id
    doc: STAC collection id containing the granule
    label: Collection id
    type: string
    default: ESACCI_Biomass_L4_AGB_V4_100m
  - name: granule_id
    doc: STAC item (granule) id to clip
    label: Granule id
    type: string
    default: S50W080_ESACCI-BIOMASS-L4-AGB-MERGED-100m-2020-fv4.0
  - name: asset_name
    doc: Name of the raster asset to clip
    label: Asset name
    type: string?
    default: estimates
  - name: bbox
    doc: Clip bounding box as 'MINX MINY MAXX MAXY' in EPSG:4326
    label: Bounding box
    type: string
    default: -78 -58 -76 -56
  - name: output_file
    doc: Name of the output COG
    label: Output filename
    type: string?
    default: clipped.tif

outputs:
  - name: out
    type: Directory
