name: biomass-change
on:
  push:
    branches:
      - main
    paths:
      - 'biomass_change/**'
      - '.github/workflows/biomass-change.yml'
      - '.github/workflows/generate-app-pack.yml'

jobs:
  build:
    uses: ./.github/workflows/generate-app-pack.yml
    with:
      example-dir: biomass_change
    secrets: inherit
