name: color-to-greyscale
on:
  push:
    branches:
      - main
    paths:
      - 'color_to_greyscale/**'
      - '.github/workflows/color-to-greyscale.yml'
      - '.github/workflows/generate-app-pack.yml'

jobs:
  build:
    uses: ./.github/workflows/generate-app-pack.yml
    with:
      example-dir: color_to_greyscale
    secrets: inherit
