name: estimate-pi
on:
  push:
    branches:
      - main
    paths:
      - 'estimate_pi/**'
      - '.github/workflows/estimate-pi.yml'
      - '.github/workflows/generate-app-pack.yml'

jobs:
  build:
    uses: ./.github/workflows/generate-app-pack.yml
    with:
      example-dir: estimate_pi
      register-endpoint: https://api.uat.maap-project.org/api/ogc/processes
    secrets: inherit
