name: fortran-example
on:
  push:
    branches:
      - main
    paths:
      - 'fortran_example/**'
      - '.github/workflows/fortran-example.yml'
      - '.github/workflows/build-app-pack.yml'

jobs:
  build:
    uses: ./.github/workflows/build-app-pack.yml
    with:
      example-dir: fortran_example
    secrets: inherit
